= RPM Packaging Guide

[[abstract]]
== Abstract

// FIXME RENAME "General Topics and Background" TO "Preparing Source Code for Packaging" ?

// FIXME MOVE "ABSTRACT", "DOCUMENT CONVENTIONS", "PREREQUISITES", AND "CONTRIBUTING TO THIS GUIDE" TO SEPARATE FILES
// FIXME ADD "LEGAL NOTICE" BEFORE THE ABSTRACT

// FIXME WHOLE GUIDE: MAKE MARKUP CONSISTENT, ESPECIALLY FOR TERMS
// FIXME WHOLE GUIDE: MAKE TONE AND POINT OF VIEW CONSISTENT ("WE" VERSUS "YOU" AND SIMILAR)
// FIXME WHOLE GUIDE: MAKE TERMS SPELLED CONSISTENTLY: RPM Packager, RPM Package, Binary RPM, Source RPM, AND SO ON

// FIXME WHOLE GUIDE: MAKE SECTION NAMES MORE SPECIFIC
// FIXME WHOLE GUIDE: MAKE SECTION NAMES ACTION-ORIENTED
// FIXME WHOLE GUIDE: ADD MORE STRUCTURE, ESPECIALLY FOR PROCEDURES

// FIXME RENAME GENERAL BACKGROUND AND RPM GUIDE CHAPTERS

The RPM Packaging Guide documents:

* How to prepare source code for packaging into an RPM. This is for people with no background in software development. See <<general-background.adoc#general-topics-and-background>>.
* How to package source code into an RPM. This is for software developers who need to package software into RPMs. See <<rpm-guide.adoc#rpm-packaging-guide>>.
* Advanced packaging scenarios. This is for RPM packagers dealing with advanced RPM Packaging scenarios. See <<appendix.adoc#appendix>>.

// FIXME MAYBE MOVE THIS PARAGRAPH FROM THE ABSTRACT TO INTRODUCTION?
The <<general-background.adoc#general-topics-and-background>> is a tutorial that
prepares people with no experience in software development to RPM Packaging. The
<<rpm-guide.adoc#rpm-packaging-guide>> is a tutorial that guides through basic
RPM Packaging. Follow both tutorials from beginning to end. The
<<appendix.adoc#appendix>> is reference material for information on RPM
Packaging beyond the basics.

[[document-conventions]]
== Document Conventions

The document uses the following conventions:

* Command output and contents of text files, including source code, are placed
in blocks:
+
[source,bash]
----
$ tree ~/rpmbuild/
/home/user/rpmbuild/
|-- BUILD
|-- RPMS

[command output trimmed]

----
+
[source,txt]
----
Name:           bello
Version:
Release:        1%{?dist}
Summary:

[file contents trimmed]

----
+
[source,python]
----
#!/usr/bin/env python

print("Hello World")

----

Topics of interest or vocabulary terms are referred to either as URLs to their
respective documentation or website, in **bold**, or in __italics__. The first
occurences of some terms link to their respective documentation.
// FIXME LAST SENTENCE ONLY IN UPSTREAM VERSION

Names of utilities, commands, and things normally found in code are written in
``monospace`` font.

[[prerequisites]]
== Prerequisites

To follow this tutorial, you need these packages installed:

NOTE: Some of these packages are installed by default on Fedora, RHEL, and
CentOS. They are listed explicitly to show which tools are used in this guide.
// FIXME CONDITIONALS

*   For https://getfedora.org/[Fedora]:

[source,bash]
----
$ dnf install gcc rpm-build rpm-devel rpmlint make python bash coreutils diffutils patch rpmdevtools

----

*   For https://www.redhat.com/en/technologies/linux-platforms[RHEL] or https://www.centos.org/[CentOS] (this guide assumes version 7.x of either):

[source,bash]
----
$ yum install gcc rpm-build rpm-devel rpmlint make python bash coreutils diffutils patch rpmdevtools

----

// FIXME CONDITIONALS

[[contributing-to-this-guide]]
== Contributing to this guide
// FIXME THIS SECTION ONLY FOR UPSTREAM?

You can contribute to this guide by submitting an issue or a pull request on
https://github.com/redhat-developer/rpm-packaging-guide[the GitHub repository].

Both forms of contribution are greatly appreciated and welcome.

Feel free to file an issue ticket with feedback, submit a pull request
https://github.com/redhat-developer/rpm-packaging-guide[on GitHub], or both!
