[[introduction]]
= Introduction

The RPM Packaging Guide documents:

How to prepare source code for packaging into an RPM.:: This is for people with
no background in software development. See
xref:preparing-software-for-packaging[].

How to package source code into an RPM.:: This is for software developers who
need to package software into RPMs. See xref:packaging-software[].

Advanced packaging scenarios.:: This is a reference material for RPM packagers
dealing with advanced RPM Packaging scenarios. See xref:advanced-topics[].

ifdef::community[]
[[pdf-version]]
== PDF Version

You can also download a
https://rpm-packaging-guide.github.io/rpm-packaging-guide.pdf[PDF version of
this document].
endif::community[]

[[document-conventions]]
== Document Conventions

The document uses the following conventions:

* Command output and contents of text files, including source code, are placed
in blocks:
+
[source,bash]
----
$ tree ~/rpmbuild/
/home/user/rpmbuild/
|-- BUILD
|-- RPMS

[command output trimmed]
----
+
[source,txt]
----
Name:           bello
Version:
Release:        1%{?dist}
Summary:

[file contents trimmed]
----
+
[source,python]
----
#!/usr/bin/env python

print("Hello World")
----

* Topics of interest or vocabulary terms are referred to either as URLs to their
respective documentation or website, in **bold**, or in __italics__.
ifdef::community[]
The first occurrences of some terms link to their respective documentation.
endif::community[]

*   Names of utilities, commands, and things normally found in code are written in
``monospace`` font.

ifdef::community[]
include::contributing-to-this-guide.adoc[leveloffset=+1]
endif::community[]
