[[introduction]]
= Introduction

The RPM Packaging Guide documents:

How to prepare source code for packaging into an RPM.:: This is for people with
no background in software development. See xref:preparing-software-for-packaging[].

How to package source code into an RPM.:: This is for software developers who
need to package software into RPMs. See xref:packaging-software[].

Advanced packaging scenarios.:: This is a reference material for RPM packagers
dealing with advanced RPM Packaging scenarios. See xref:advanced-topics[].

[[document-conventions]]
== Document Conventions

The document uses the following conventions:

* Command output and contents of text files, including source code, are placed
in blocks:
+
[source,bash]
----
$ tree ~/rpmbuild/
/home/user/rpmbuild/
|-- BUILD
|-- RPMS

[command output trimmed]
----
+
[source,txt]
----
Name:           bello
Version:
Release:        1%{?dist}
Summary:

[file contents trimmed]
----
+
[source,python]
----
#!/usr/bin/env python

print("Hello World")
----

* Topics of interest or vocabulary terms are referred to either as URLs to their
respective documentation or website, in **bold**, or in __italics__.
ifdef::community[]
The first occurrences of some terms link to their respective documentation.
endif::community[]

*   Names of utilities, commands, and things normally found in code are written in
``monospace`` font.

[[prerequisites]]
== Prerequisites

To follow this tutorial, you need these packages installed:

ifdef::community[]
NOTE: Some of these packages are installed by default on https://getfedora.org/[Fedora], https://www.centos.org/[CentOS] and https://www.redhat.com/en/technologies/linux-platforms[RHEL]. They are listed explicitly to show which tools are used in this guide.
endif::community[]

ifdef::rhel[]
NOTE: Some of these packages are installed by default on https://www.redhat.com/en/technologies/linux-platforms[RHEL]. They are listed explicitly to show which tools are used in this guide.
endif::rhel[]

ifdef::community[]

[source,bash]
----
$ dnf install gcc rpm-build rpm-devel rpmlint make python bash coreutils diffutils patch rpmdevtools

$ yum install gcc rpm-build rpm-devel rpmlint make python bash coreutils diffutils patch rpmdevtools
----
endif::community[]

ifdef::rhel[]

[source,bash]
----
$ yum install gcc rpm-build rpm-devel rpmlint make python bash coreutils diffutils patch rpmdevtools
----

endif::rhel[]

ifdef::community[]
include::contributing-to-this-guide.adoc[leveloffset=+1]
endif::community[]
