name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Convert and publish AsciiDoctor
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Convert AsciiDoc
      id: documents
      uses: Analog-inc/asciidoctor-action@f6305152cb5089da83f50d4d80e26f63d264ae34 #master
      with:
        shellcommand: "./.github/workflows/asciidoc.sh"
    - name: Save AsciiDoc
      uses: actions/upload-artifact@v1
      with:
        name: Docs
        path: ./output/
    - name: Push to another repository
      uses: cpina/github-action-push-to-another-repository@9e487f29582587eeb4837c0552c886bb0644b6b9 #main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'output'
        destination-github-username: 'rpm-packaging-guide'
        destination-repository-name: 'rpm-packaging-guide.github.io'
        user-email: pkovar@redhat.com
        target-branch: master
